### ISSUE TITLE
Telegram-desktop freezes when viewing an image on Arch Linux or ArcoLinux

### ISSUE THREAD

**Issue by erikdubois** [leftwm/leftwm#653]
**Describe the bug**
Telegram-desktop freezes when viewing an image on Arch Linux or ArcoLinux

**To Reproduce**
0. use telegram-desktop - telegram-desktop 3.4.3-2
1. Go to a channel and view an image - exit - try to see the next image then freeze occurs

We use our own pkgbuild - based on your code of r567.e93422f-1
https://github.com/leftwm/leftwm/commit/e93422f033475b1d2595a17f188baba78394dd9c

**Expected behavior**
Image closes and telegram does not freeze 

**Video**
https://youtu.be/qW2zeng2lmk

**Environment:**
 - OS/Distro: ArcoLinux and Arch Linux
 - Output of `leftwm-check` - all ok - all green

I have been observing this for several weeks now.
My workaround was to kill telegram and restart it.

Thinking it will be an update of Telegram gone wrong.

But Telegram works fine on XFCE4 - installed on the same machine leftwm is. Making the conclusion that it must be something related to leftwm.

I hope you can figure this one out. Users have been reporting this as well. Since it is no longer "just me", I post this issue.

**Comment by VuiMuich** [comment]
Can you check, if in your leftwm session you have launched a notification daemon?
I can remember discord behaving very strange (up to basically freezing the graphical-session) when it tries to notify the system and can't reach the daemon. XFCE4 most probable is starting it's daemon by default.

(TBH. haven't had time yet to watch your video, so this is just a wild guess based on the experience with discord)

**Comment by erikdubois** [comment]
xfce4-notifyd is running

**Comment by erikdubois** [comment]
Same issue if it is not around

**Comment by mautamu** [comment]
Does the image get placed beneath the tiled window? Might help to resize the telegram window and see if it's hiding beneath it. Noticed something similar with LibreOffice today.

**Comment by arcolinuxz** [comment]
Nothing behind it either

**Comment by AethanFoot** [comment]
Ok, from what I can tell the issue is that Telegram attempts to re-use the previous "image viewer window" again and crashes as the window is not re-mapped. How we handle this depends on whether it is working on other window managers. To explain, as we forget about the window in the current system when it is unmapped (this is likely to change soon), we get a configure request for a window we don't know about (on the second time round). We then send of needed configure events for the unmapped window then stop (this was added to fix issues with xterm). If it is working with other wm's, then it is clearly expected that we have to remap the window. Otherwise if it isn't working, telegram is expected to send a map event when reopening the window.

The frustrating part is to fix this in the first explanation requires a rework where we add windows when created (instead of mapped) and remove windows when destroyed (instead of unmapped). This means it may take a little longer then wanted, however this would fix issues like #591 and picom fading as when hiding a window we can unmap it instead of moving it of screen. 

Many Thanks!

**Comment by VuiMuich** [comment]
🛑🛑🛑
Attention!

#663 currently breaks your running state, when being reverted. All hidden windows will get unmapped and cannot be reattached to leftwm by Soft or Hard reload. So be careful when checking this out.

**Comment by arcolinuxz** [comment]
Latest build on r573.43a278a-1 has the same result for telegram.
It freezes.

**Comment by arcolinuxz** [comment]
Issue is solved today - new telegram package -  3.4.8-1 -  and release of leftwm  r579.52e340b-1

**Comment by n1s** [comment]
hmm I'm still facing this issue. Running the latest version. Would you know why?

```
~  leftwm-check                                                                                                      ✔ ╱   18:19:24
:: LeftWM version: 0.3.0
:: LeftWM git hash: 9ad1dfd
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
 ~  pacman -Si telegram-desktop                                                                                       ✔ ╱   18:19:35
Repository      : community
Name            : telegram-desktop
Version         : 3.5.2-1
Description     : Official Telegram Desktop client
Architecture    : x86_64
URL             : https://desktop.telegram.org/
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : hunspell  ffmpeg4.4  hicolor-icon-theme  lz4  minizip  openal  ttf-opensans  qt6-imageformats  qt6-svg  qt6-wayland
                  qt6-5compat  xxhash  glibmm  rnnoise  pipewire  libxtst  libxrandr  jemalloc  abseil-cpp  libdispatch
Optional Deps   : webkit2gtk: embedded browser features
                  xdg-desktop-portal: desktop integration
Conflicts With  : None
Replaces        : None
Download Size   : 25.62 MiB
Installed Size  : 69.20 MiB
Packager        : Sven-Hendrik Haase <svenstaro@gmail.com>
Build Date      : Wed 09 Feb 2022 16:46:09 CET
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

**Comment by arcolinuxz** [comment]
We have no issue on ArcoLinux
version r597.9ad1dfd-1 running currently
package on our repo
you can try that one

**Comment by n1s** [comment]
> We have no issue on ArcoLinux version r597.9ad1dfd-1 running currently package on our repo you can try that one
> 
> :: LeftWM version: 0.3.0 :: LeftWM git hash: [9ad1dfd](https://github.com/leftwm/leftwm/commit/9ad1dfdab1a6deeaefd73416ce88b325439a79af)

hmm it appears that I had some mess with my packages. After a clean install with cargo it went ok - thank you.
