### ISSUE TITLE
Theme is incompatible with version of Leftwm

### ISSUE THREAD

**Issue by MrCockles** [leftwm/leftwm#679]
I have been trying to change the theme along with my OS's wiki. [](https://www.arcolinuxd.com/3-how-to-change-the-theme-in-leftwm/ )
I get this error instead of the picture in the wiki 
![ArcoLinux-2022-01-26-1643223832_screenshot_1920x1080](https://user-images.githubusercontent.com/40811670/151230203-379d1fc1-b52a-43a9-84dd-935b7c5fdaf9.jpg)
![ArcoLinux-2022-01-26-1643223905_screenshot_1920x1080](https://user-images.githubusercontent.com/40811670/151230208-45aa65ce-7d8d-4e4d-b3aa-a43842e6cf6d.jpg)
I tried googling the error message, but I got nothing. this feels like a simple fix, but I don't know where else to go for troubleshooting.

**Comment by MrCockles** [comment]
the wiki that I used is here https://www.arcolinuxd.com/3-how-to-change-the-theme-in-leftwm/

**Comment by VuiMuich** [comment]
Welcome Adventurer!
You came to the exact right place with your problem. There is one other place that would've been equally good place and that is our community discord.

To be fair, I have yet to check what is exactly the issue with the Dracula theme, but I guess it would use a feature of the yet to be released `leftwm` version `3.0.0`.
You are probably on the regular `leftwm` AUR package and not on the `leftwm-git` package, aren't you? Could you please also post the output of `leftwm-check`?

**Comment by MrCockles** [comment]
![ArcoLinux-2022-01-26-1643226353_screenshot_1920x1080](https://user-images.githubusercontent.com/40811670/151235637-88dd44d6-21b7-46e2-a08b-c4cbd6b982f8.jpg)
here you go

**Comment by VuiMuich** [comment]
Just checked, its actually the `dracula` theme that is out of date.

To manually fix this on your machine, please go to `~/.config/leftwm/themes/current` and edit both the `up` script:
```diff
- echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe
+ leftwm-command "LoadTheme $SCRIPTPATH"
```
and `down` script:
```diff
- echo "UnloadTheme" > $XDG_RUNTIME_DIR/leftwm/commands.pipe
+ leftwm-command UnloadTheme
```

**Comment by MrCockles** [comment]
Ok, thanks! is this the same process with the other themes also?

**Comment by MrCockles** [comment]
I think I messed something up, I removed the red lines in your post from the script, and added the green lines in their place, updated, then tried to apply the theme and got the same error as before. did I misinterpret your instructions?

**Comment by PeterDauwe** [comment]
In the up script the green line must be :
leftwm-command "LoadTheme $SCRIPTPATH"/theme.toml

**Comment by mautamu** [comment]
Leftwm-theme doesn't know that you've made the change, what you can do is edit ~/.config/leftwm/themes.toml and set leftwm_versions = "*" under Dracula Rounded.

**Comment by VuiMuich** [comment]
> In the up script the green line must be :
> 
> leftwm-command "LoadTheme $SCRIPTPATH"/theme.toml
> 
> 

Oh, yeah, my bad.
But actually the end-quote is misplaced in yours I think. Should be 
```shell
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"
```

**Comment by AethanFoot** [comment]
We need an automatic way to update the submodules in community themes. Dracula rounded should be updated on the main branch with these changes.

**Comment by MrCockles** [comment]
I corrected the line in the up script, changed the leftwm version line in the theme.toml to "*". I ran leftwm-theme update, then tried to apply the Dracula theme with no luck. same error. for grins and giggles I tried to apply Ocean-night, and it seemed to work at first. but as soon as I switched back to leftwm from awesome my computer froze up, tried Epitaph, and it didn't freeze, it rebooted my login manager. Is this problem linked at all to the out-of-date themes?

**Comment by VentGrey** [comment]
Epitaph rebooted your login manager :scream: ? How so? If you happen to know can you please open an issue in the repository so I can take a look at that issue? :thinking:

**Comment by MrCockles** [comment]
done, let me know when you figure out what the problem is.

**Comment by mautamu** [comment]
> We need an automatic way to update the submodules in community themes. Dracula rounded should be updated on the main branch with these changes.

Tagging https://github.com/leftwm/leftwm-theme/issues/33

**Comment by MarkuBu** [comment]
I compiled leftwm from git. Still the same problem. Only the ocean night theme is working after manually make up, down and change_to_tag executabel
