### ISSUE TITLE
Improve stacking

### ISSUE THREAD

**Issue by VuiMuich** [leftwm/leftwm#864]
### Describe the enhancement

There are some cases, where `leftwm` stacking is subpar, and might be even a bit of xorg specs. I started researching the docs on xorg, ewmh and icccm on this topic.

Two cases currently come to mind right now(will add more, when I remember them again):
1. when a window is `fullscreen` and a scratchpad is pulled up, the scratchpad should ideally be on top of the fullscreen window
2. in `eww` (and as it uses gtk very closely to spec, conscutively probably a bunch of other gtk apps as well) some stacking related wm-hints are kind of ignored or applied wrong (will need to gather more details on this).

Instead of fixing this per case I wanted to start this issue to investigate if we can implement some general improvement by following the defined standards more closely.

tbc.

### How important is this enhancement to you?

Would be nice to have

### How important do you think is this enhancement for the average LeftWM user?

Would probably be nice to have

**Comment by charbelnicolas** [comment]
I was trying out leftwm the other day and I figured that it doesn't play nice with the rofi window switcher when using the monocle layout. This might probably be related...

**Comment by VuiMuich** [comment]
> I was trying out leftwm the other day and I figured that it doesn't play nice with the rofi window switcher when using the monocle layout. This might probably be related...

Can you please provide a bit more details? Also maybe check the latest git version, we just merged a fix for a rofi related regression.

**Comment by charbelnicolas** [comment]
I tried the latest git version and it still shows the same issue. If you are using the monocle layout, if you switch windows with rofi, it won't do anything unless said window you are switching to is in another different workspace (tag).

https://user-images.githubusercontent.com/14960414/194969583-90a69551-11d0-4538-928b-be42bc30aae2.mp4

**Comment by VuiMuich** [comment]
Sorry, I completely misread your fist post by skipping the "switching" part.
> I tried the latest git version and it still shows the same issue. If you are using the monocle layout, if you switch windows with rofi, it won't do anything unless said window you are switching to is in a different workspace (tag).
> 
>  2022-10-10_18-54-48.mp4

You are using `rofi -show windowcd` right? This seems broken in general. I think this worked at one point, so we probably have a regression here. Thanks for reporting this!

**Comment by charbelnicolas** [comment]
> Sorry, I completely misread your fist post by skipping the "switching" part.
> 
> > I tried the latest git version and it still shows the same issue. If you are using the monocle layout, if you switch windows with rofi, it won't do anything unless said window you are switching to is in a different workspace (tag).
> > 2022-10-10_18-54-48.mp4
> 
> You are using `rofi -show windowcd` right? This seems broken in general. I think this worked at one point, so we probably have a regression here. Thanks for reporting this!
> 
> `wmctrl -a` seems broken as well and I am pretty sure that worked before.

Hello @VuiMuich, yes, I'm using `rofi -show window`.

**Comment by VuiMuich** [comment]
> > Sorry, I completely misread your fist post by skipping the "switching" part.
> > > I tried the latest git version and it still shows the same issue. If you are using the monocle layout, if you switch windows with rofi, it won't do anything unless said window you are switching to is in a different workspace (tag).
> > > 2022-10-10_18-54-48.mp4
> > 
> > 
> > You are using `rofi -show windowcd` right? This seems broken in general. I think this worked at one point, so we probably have a regression here. Thanks for reporting this!
> > `wmctrl -a` seems broken as well and I am pretty sure that worked before.
> 
> Hello @VuiMuich, yes, I'm using `rofi -show window`.

You might want to try #887 it fixes the issue on my side, but I am not 100% certain yet if my patch doesn't come with some unwanted side effects so some testing and feedback would be welcome.
